version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
    post_build:
      - echo Build completed successfully
artifacts:
  files:
    - target/Student-Service.jar
  discard-paths: yes